### ISSUE TITLE
compose install issue

### ISSUE THREAD

**Issue by bstrokevin** [klaviyo/php-klaviyo#20]
klaviyo git:(master) ✗ composer require klaviyo/php-sdk
Using version ^2.1 for klaviyo/php-sdk
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)

Installation failed, deleting ./composer.json.

                                                                                           
  [ErrorException]                                                                         
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  
                                                                                           

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by remstone7** [comment]
Hi @bstrokevin - I wasn't able to reproduce this, could you please provide php/composer versions?
```
~/Desktop/comp$ composer require klaviyo/php-sdk
Using version ^2.1 for klaviyo/php-sdk
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing klaviyo/php-sdk (2.1.1): Downloading (100%)         
Writing lock file
Generating autoload files
~/Desktop/comp$ ls
composer.json  composer.lock  vendor/
```
