### ISSUE TITLE
Is there any reference for flows?

### ISSUE THREAD

**Issue by emreisik95** [klaviyo/php-klaviyo#21]
Hey there, 

I'm trying to get our flow metrics. Is there any reference or docs about it? 

Thank you.

**Comment by remstone7** [comment]
We don't have a specific endpoint to fetch metrics from flows but you can take a look at the following link on how to export conversion data, which you should be able to aggregate for flows: https://help.klaviyo.com/hc/en-us/articles/360040093732-Export-Conversion-Data
