### ISSUE TITLE
Integrating the product feed for other ecommerce platforms

### ISSUE THREAD

**Issue by franclin** [klaviyo/php-klaviyo#22]
We are trying to implement the Product Feed as described here (https://help.klaviyo.com/hc/en-us/articles/115005082787-Product-Feeds-and-Recommendations) for one of our customers (coronacigar.com). The online documentation doesn’t give a detailed procedure of how to get this done with third party shopping cart. 

 As far as I understand, the feed is meant to be pulled by Shopify from the retailer’s webstore. However, I think this feed should follow a specific format as well as being returned in a specific format (JSON or XML).

**Comment by smoucka** [comment]
Hi @franclin 

Klaviyo's Product Feed feature utilizes the catalog stored in your Klaviyo account. If you've integrated this customer's Shopify store with a Klaviyo account then this catalog sync is handled automatically. If you need to access to a third party catalog that is not synced through Shopify you'll want to set up a custom catalog. This is detailed briefly in our [Custom Integration documentation here](https://help.klaviyo.com/hc/en-us/articles/115005082927-Integrate-a-Standard-Ecommerce-Platform#catalog-feed-integration10). You'll ultimately want to reach out to our Support Team for help in setting this up (link provided in documentation).

I'm going to mark this issue as closed.
