### ISSUE TITLE
Exception When Time Isn't Provided

### ISSUE THREAD

**Issue by cbarranco** [klaviyo/php-klaviyo#23]
The change to EventModel in commit 8d73402 in PR #19 removes the check for $config['time'] being empty. Per the documentation, time is not a required parameter so I believe this change creates a new bug. I am getting an exception when attempting to track an event because I am not providing time, and the call to is_int($config['time']) is throwing an undefined index PHP error.

**Comment by remstone7** [comment]
yes adding this in #24

**Comment by remstone7** [comment]
resolved in 2.2.2
