### ISSUE TITLE
Exception When Time Is Provided

### ISSUE THREAD

**Issue by cbarranco** [klaviyo/php-klaviyo#31]
If a time is provided in the $config array, an error is thrown on line 56 of EventModel:

> Cannot use object of type DateTime as array        

`56   $this->time = !empty($config['time']) ? strtotime( $time['date'] ) : null;`

You cannot access the 'date' property of a DateTime object directly, it needs to be changed to

`56   $this->time = !empty($config['time']) ? strtotime( $time->format('Y-m-d H:i:s') : null;`

**Comment by remstone7** [comment]
resolved in 2.2.2
