### ISSUE TITLE
Event "Ordered Product" not all product items tracked

### ISSUE THREAD

**Issue by DannyDan** [klaviyo/php-klaviyo#35]
I have 4 items in my order and not all products are tracked when sending the event "Ordered Product". only 2 events are sent to Klaviyo regarding "Ordered Product" when checking through the Klaviyo backend inside my customer profile. 
I checked the eventdata during checkout and they are correct for all 4 items.

**Comment by DannyDan** [comment]
@kamil-klasicki 
no support?

**Comment by remstone7** [comment]
Hi @DannyDan could you share the calls you're making w/ some event data?  If you don't feel comfortable sharing here, please write into our support and our team will take this so we can troubleshoot further for your specific account issue.  https://help.klaviyo.com/hc/en-us/articles/115001002272-How-to-Contact-Support

**Comment by DannyDan** [comment]
Thanks. I used the support form.

**Comment by remstone7** [comment]
Great - going to close this out, i just assigned the ticket someone should get back to you shortly!
