### ISSUE TITLE
Rate limiting gives fatal exception

### ISSUE THREAD

**Issue by ahyldig** [klaviyo/php-klaviyo#37]
When rate limiting happens it is suppose to throw an exception of type KlaviyoRateLimitException but because of incorrect parameters passed when initializing the exception, it fails and throws a fatal regular Exception instead.

Exception:
Uncaught Error: Wrong parameters for Klaviyo\Exception\KlaviyoRateLimitException([string $message [, long $code [, Throwable $previous = NULL]]]) in /klaviyo/php-sdk/src/KlaviyoAPI.php:182

Cause of error:
KlaviyoRateLimitException is expecting a string as the first parameter but the KlaviyoAPI class attempts to pass an Array.

**Comment by remstone7** [comment]
Thanks @ahyldig will fix this

**Comment by remstone7** [comment]
all set in v2.2.4 updated on composer
