### ISSUE TITLE
400 status code does not show details

### ISSUE THREAD

**Issue by Kalo79** [klaviyo/php-klaviyo#40]
In "handleResponse" an exception is thrown when the status code is !=200, but that exception only contains the status code and does not include any details from the response.
The 400 status may be due to different reasons and it would be nice if the exception contains the exact reason returned in the response.

**Comment by remstone7** [comment]
Hey @Kalo79 - yes, we will add this!

**Comment by Kalo79** [comment]
Here is how I'm doing it for now. It works for me.
`
else if ( $statusCode != 200 ) {
            $ret=$statusCode.' ('.$this->decodeJsonResponse( $response )['detail'].')';
            throw new KlaviyoException( sprintf( self::ERROR_NON_200_STATUS, $ret ) );
        }
`
