### ISSUE TITLE
Is this project auto generated?

### ISSUE THREAD

**Issue by loevgaard** [klaviyo/php-klaviyo#44]
Is this project auto generated? If not I will add some PRs improving the overall quality and developer experience if that would be okay?

**Comment by remstone7** [comment]
It's not autogenerated, what changes are you looking to make?

**Comment by loevgaard** [comment]
Lots
- Make a CI pipeline
- Use Psalm
- Up the requirement to PHP 7.4 including the code
- Add more tests
- Overall: make it more robust

What do you think? :)

**Comment by remstone7** [comment]
all of that looks good we'd definitely appreciate it!

For php 7.4, would you be making this the minimum requirement or just expanding to support it?
For the ci, what would you be using?

**Comment by loevgaard** [comment]
Here is a first PR: https://github.com/klaviyo/php-klaviyo/pull/45

**Comment by remstone7** [comment]
okay cool 👍 will review on the pr's, closing this issue!
