### ISSUE TITLE
When is the next release coming out?

### ISSUE THREAD

**Issue by vladsh91** [klaviyo/php-klaviyo#54]
Hello,

At the moment I am using 2.2.5 tag, but I am going to use Data Privacy API V2 due to GDPR. I see that support for the deletion requests was added into the master but it still isn't released. I don't want to use an unstable master code. So, just have a question, when is the next release coming out?

Thanks in advance!

**Comment by smoucka** [comment]
Thanks for your interest! This should get released before the end of the week.

**Comment by vladsh91** [comment]
@smoucka that's great, will wait then, thanks so much :)
