### ISSUE TITLE
How can track multiple products

### ISSUE THREAD

**Issue by syamvilakudy** [klaviyo/php-klaviyo#7]
I have to tract multiple product purchase to Klaviyo. given example with only one SKU.
<pre>$tracker = new Klaviyo("YOUR_TOKEN");
$tracker->track(
    'Purchased item',
    array('$email' => 'someone@example.com', '$first_name' => 'Bill', '$last_name' => 'Shakespeare'),
    array('Item SKU' => 'ABC123', 'Payment Method' => 'Credit Card'),
    1354913220
);</pre>

I have multiple SKU with single order. How can I achieve this ?

**Comment by Daniel-pak** [comment]
Having this issue as well.

**Comment by remstone7** [comment]
closing out but you have to do 1 product at time for an "item" event
